#!/usr/bin/env python3
"""Export fixed-point laser-range registration LUTs for FPGA use."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


def quantize(value: float, frac_bits: int) -> int:
    return int(round(float(value) * (1 << frac_bits)))


def quantize_affine(matrix: list[list[float]], frac_bits: int) -> list[list[int]]:
    if len(matrix) != 2 or any(len(row) != 3 for row in matrix):
        raise ValueError("affine matrix must be 2x3")
    return [[quantize(value, frac_bits) for value in row] for row in matrix]


def load_config(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    required = ["fixed_point", "rangefinder", "fallback", "range_bins", "image_geometry"]
    missing = [name for name in required if name not in payload]
    if missing:
        raise ValueError(f"missing required config sections: {', '.join(missing)}")
    return payload


def build_entry(name: str, item: dict[str, Any], affine_frac_bits: int) -> dict[str, Any]:
    matrix = item["output_to_raw_lwir_affine"]
    return {
        "name": name,
        "min_distance_mm": int(item.get("min_distance_mm", 0)),
        "max_distance_mm": int(item.get("max_distance_mm", 0)),
        "affine_float": matrix,
        "affine_q": quantize_affine(matrix, affine_frac_bits),
        "residual_shift_xy": item.get("residual_shift_xy", [0, 0]),
        "fusion_alpha": int(item.get("fusion_alpha", 96)),
        "lwir_gain_q": quantize(float(item.get("lwir_gain", 1.0)), 8),
        "lwir_offset": int(item.get("lwir_offset", 0)),
        "source": item.get("source", item.get("reason", "")),
    }


def write_header(path: Path, payload: dict[str, Any]) -> None:
    entries = payload["entries"]
    fallback = payload["fallback"]
    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Auto-generated by peizhun_jiguang/scripts/export_laser_lut.py")
    lines.append("// Fixed-point affine coefficients use Q format with LASER_AFFINE_FRAC_BITS fractional bits.")
    lines.append("")
    lines.append(f"#define LASER_OUTPUT_WIDTH {payload['image_geometry']['output_width']}")
    lines.append(f"#define LASER_OUTPUT_HEIGHT {payload['image_geometry']['output_height']}")
    lines.append(f"#define LASER_RAW_LWIR_WIDTH {payload['image_geometry']['raw_lwir_width']}")
    lines.append(f"#define LASER_RAW_LWIR_HEIGHT {payload['image_geometry']['raw_lwir_height']}")
    lines.append(f"#define LASER_AFFINE_FRAC_BITS {payload['fixed_point']['affine_frac_bits']}")
    lines.append(f"#define LASER_RANGE_BIN_COUNT {len(entries)}")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  int min_distance_mm;")
    lines.append("  int max_distance_mm;")
    lines.append("  int affine_q[2][3];")
    lines.append("  int fusion_alpha;")
    lines.append("  int lwir_gain_q;")
    lines.append("  int lwir_offset;")
    lines.append("} laser_range_bin_t;")
    lines.append("")
    lines.append("static const laser_range_bin_t LASER_FALLBACK_BIN = {")
    lines.append(f"  {fallback['min_distance_mm']}, {fallback['max_distance_mm']},")
    lines.append("  {")
    for row in fallback["affine_q"]:
        lines.append(f"    {{{row[0]}, {row[1]}, {row[2]}}},")
    lines.append("  },")
    lines.append(f"  {fallback['fusion_alpha']}, {fallback['lwir_gain_q']}, {fallback['lwir_offset']}")
    lines.append("};")
    lines.append("")
    lines.append("static const laser_range_bin_t LASER_RANGE_BINS[LASER_RANGE_BIN_COUNT] = {")
    for entry in entries:
        lines.append("  {")
        lines.append(f"    {entry['min_distance_mm']}, {entry['max_distance_mm']},")
        lines.append("    {")
        for row in entry["affine_q"]:
            lines.append(f"      {{{row[0]}, {row[1]}, {row[2]}}},")
        lines.append("    },")
        lines.append(f"    {entry['fusion_alpha']}, {entry['lwir_gain_q']}, {entry['lwir_offset']}")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export(config_path: Path, output_dir: Path) -> dict[str, Any]:
    config = load_config(config_path)
    output_dir.mkdir(parents=True, exist_ok=True)
    affine_frac_bits = int(config["fixed_point"].get("affine_frac_bits", 16))

    fallback = build_entry("fallback", config["fallback"], affine_frac_bits)
    fallback["min_distance_mm"] = int(config["rangefinder"].get("valid_distance_min_mm", 0))
    fallback["max_distance_mm"] = int(config["rangefinder"].get("valid_distance_max_mm", 0))
    entries = [
        build_entry(str(item.get("name", f"bin_{idx}")), item, affine_frac_bits)
        for idx, item in enumerate(config["range_bins"])
    ]
    payload = {
        "source_config": str(config_path),
        "target_hardware": config.get("target_hardware", {}),
        "fixed_point": config["fixed_point"],
        "image_geometry": config["image_geometry"],
        "rangefinder": config["rangefinder"],
        "fallback": fallback,
        "entries": entries,
    }

    (output_dir / "laser_lut.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    with (output_dir / "laser_lut.csv").open("w", newline="", encoding="utf-8") as handle:
        fieldnames = [
            "name",
            "min_distance_mm",
            "max_distance_mm",
            "m00_q",
            "m01_q",
            "m02_q",
            "m10_q",
            "m11_q",
            "m12_q",
            "fusion_alpha",
            "lwir_gain_q",
            "lwir_offset",
        ]
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for entry in [fallback] + entries:
            row = {
                "name": entry["name"],
                "min_distance_mm": entry["min_distance_mm"],
                "max_distance_mm": entry["max_distance_mm"],
                "m00_q": entry["affine_q"][0][0],
                "m01_q": entry["affine_q"][0][1],
                "m02_q": entry["affine_q"][0][2],
                "m10_q": entry["affine_q"][1][0],
                "m11_q": entry["affine_q"][1][1],
                "m12_q": entry["affine_q"][1][2],
                "fusion_alpha": entry["fusion_alpha"],
                "lwir_gain_q": entry["lwir_gain_q"],
                "lwir_offset": entry["lwir_offset"],
            }
            writer.writerow(row)
    write_header(output_dir / "laser_lut.h", payload)
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Export fixed-point laser registration LUTs.")
    parser.add_argument("--config", type=Path, default=Path("peizhun_jiguang/config/laser_registration_params.json"))
    parser.add_argument("--output-dir", type=Path, default=Path("peizhun_jiguang/generated"))
    args = parser.parse_args()
    payload = export(args.config, args.output_dir)
    print(f"wrote {len(payload['entries'])} range bins to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
